ci:
  autoupdate_schedule: quarterly
  autofix_prs: false

repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
        files: "\\.(\
          css|less|scss\
          |graphql|gql\
          |html\
          |js|jsx\
          |json\
          |ts|tsx\
          |vue\
          |yaml|yml\
          )$"
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.5.1'
    hooks:
      - id: prettier
        name: prettier-markdown
        entry: prettier --write --parser mdx
        files: "\\.(\
          |md|markdown|mdown|mkdn\
          |mdx\
          )$"
